name: Move Closed Issue to Archive

on:
  issues:
    types: [closed]

jobs:
  archive-file:
    runs-on: ubuntu-latest

    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Move issue file
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          SOURCE_FILE="issues/$ISSUE_NUMBER.md"
          DEST_DIR="issues/closed"
          DEST_FILE="$DEST_DIR/$ISSUE_NUMBER.md"

          # Check if the source file actually exists
          if [ ! -f "$SOURCE_FILE" ]; then
            echo "File $SOURCE_FILE does not exist. Nothing to move."
            exit 0
          fi

          # Ensure the destination directory exists
          mkdir -p $DEST_DIR

          # Move the file using Git to track the rename
          echo "Moving $SOURCE_FILE to $DEST_FILE..."
          git mv $SOURCE_FILE $DEST_FILE

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # [skip ci] prevents this commit
          # from triggering other workflows.
          commit_message: "Archive closed issue #${{ github.event.issue.number }} [skip ci]"
          # We must watch all md files in the 'issues' parent
          # folder to correctly commit the 'git mv' operation
          file_pattern: "issues/**.md"