name: File to Issue Sync

on:
  push:
    paths:
      - 'issues/**.md'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # We need to fetch the full history to compare commits
          fetch-depth: 0

      - name: Find changed files and sync to issues
        env:
          # The GitHub CLI needs this token to edit the issue
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the list of modified markdown files in the 'issues' directory
          FILES=$(git diff --name-only HEAD~1 HEAD | grep '^issues/.*\.md$')

          if [ -z "$FILES" ]; then
            echo "No issue files modified."
            exit 0
          fi

          for FILE in $FILES; do
            echo "Processing $FILE..."

            if [ ! -f "$FILE" ]; then
              echo "File $FILE not found (likely deleted/moved). Skipping."
              continue
            fi

            # 1. Parse the issue number from the frontmatter
            # This relies on the frontmatter from Workflow 1
            ISSUE_NUMBER=$(grep '^number: ' $FILE | awk '{print $2}')

            if [ -z "$ISSUE_NUMBER" ]; then
              echo "Could not find issue number in $FILE. Skipping."
              continue
            fi

            # 2. Extract the body (content after the '---' frontmatter)
            BODY=$(awk 'NR>1 && /^---$/ {f=1; next} f' $FILE)

            # 3. Use the GitHub CLI to update the issue body
            echo "Syncing content to Issue #$ISSUE_NUMBER..."
            gh issue edit $ISSUE_NUMBER --body "$BODY"
          done
